### ISSUE TITLE
define_mode in QRCODE encodation 

### ISSUE THREAD

**Issue by Jonney3099** [woo-j/OkapiBarcode#18]
I am not satisfied with the codes of okapi define_mode in QRCODE encodation.we should either use one encoding mode or mixed modes.I think We should refer to ISO/IEC 18004 annex J. and,for kanji, we should check for signature bytes whether they are in the table annex H.

 if (eciMode == 20) {
            /* Shift-JIS encoding, use Kanji mode */
            japaneseLatch = true;
            inputLength = content.length();
            inputData = new int[inputLength];
            for (i = 0; i < inputLength; i++) {
                inputData[i] = (int) content.charAt(i);
            }

inputData[] is unicode value, it is right way to identify encoding mode? 

I think encodations in QRCODE is totally mess,what you think?

**Comment by woo-j** [comment]
Reguarding ECI modes:
I don't understand why we would need to check for signature bytes. The input data will always be Unicode. eciProcess() will only return ECI mode 20 if all of the characters in the input are valid Shift-JIS. For example if you added 栀 to an input string, a character which cannot be encoded with Shift-JIS, eciProcess() will return 26 and the data will be encoded using UTF-8 instead. If the ECI mode is 20 then the data put into inputData[] will consist of either characters <= 0xFF which are valid ISO-8859-1 or values > 0xFF which are valid Shift-JIS. For any other ECI the values in inputData will remain <= 0xFF, therefore:

if (inputData[i] > 0xff) {
inputMode[i] = qrMode.KANJI;

The real problem here is characters in the range 0xA0 to 0xDF. For example 0xB6 could be used to encode ¶ (from table 6) or ｶ (from table H.1), and I haven't yet found anything in the ISO standard which shows how to deal with this. Couple this with the fact that ¥ can be encoded as 0xA5 (in table 6) or 0x5C (in table H.1). To my mind this just shows why Shift-JIS should be considered a legacy standard.

Reguarding Annex J:
Okapi doesn't use the scheme in Annex J and changing it to this scheme would be non-trivial. However Okapi does use mixed modes. While I would agree that the system currently used does not always use the most efficient encoding, it gets the job done. I don't agree that it is "totally mess". The code in define_mode() should ideally be replaced with a "look ahead test" as implimented in Data Matrix, but my opinion is that this is a relatively low priority.

**Comment by woo-j** [comment]
Okapi now uses a scheme for finding the a more efficient encoding, similar to but not the same as the one outlined in Annex J of the ISO standard. As no further comment has been made about this issue I will close it.
