### ISSUE TITLE
Stacked Expanded Databar verify issue

### ISSUE THREAD

**Issue by Smith-Liang07** [woo-j/OkapiBarcode#74]
Hello, Thanks for such wonderful library.
I am using this library for so long time and I've faced one issue.
![image](https://user-images.githubusercontent.com/55897747/78674816-c5067e80-7916-11ea-87f1-d8c57b4b6da1.png)
I am not sure why verifier doesn't recognize this databar.
Generated using this code.

DatabarExpanded databar = DatabarExpanded();
databar.setStacked(true)
databar.setContent("[01]12341234123412");
and set data type to GS1
...
What is wrong or any problem in library.
I am looking forward to hearing from you soon.
Thanks.
Warm Regards.

**Comment by gredler** [comment]
I don't have access to this barcode verifier, but best I can tell the issue was probably caused by one of two things:

First, the final digit is a check digit and in this example should be 3 instead of 2, so the full (correct) example value would be "[01]12341234123413".

Second, per the spec this type of barcode should have a minimum of 2 symbol characters on the last row, which in this case requires extra padding to be added. We were not previously adding this padding, but now we are.
