### ISSUE TITLE
Support the ability to suppress code sets A and B for Code 128 Barcodes

### ISSUE THREAD

**Issue by alex-newby-hmrc** [woo-j/OkapiBarcode#76]
I understand that OkapiBarcode supports suppressing of code set C for Code 128 barcodes using the `setSuppressModeC` method. 
It would be convenient for a project I am working on if it could, through a similar mechanism, suppress code sets A and B as well. 
I would like to request this feature!

**Comment by gredler** [comment]
Going back through all bugs, and was thinking about this one a bit. Can you provide some examples where this feature would be useful? Suppressing mode C doesn't affect our ability to encode data, since numbers can also be encoded using modes A and B, but suppressing modes A or B would mean that not all data could be encoded. Just trying to wrap my head around the utility of such a feature.
